project_id = "ppyfrftmexvgnsxlhdbz"

[functions.get-customer-addresses]
verify_jwt = true

[functions.quote-submission]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true

[edge_functions]
enabled = true
port = 54322

[db]
enabled = true
port = 54322

[storage]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324

[functions.generate-title-page]
verify_jwt = false

[functions.import-jmarr-seafood]
verify_jwt = false

[functions.import-supplier-catalog]
verify_jwt = false

[functions.update-jmarr-product-images]
verify_jwt = false

[functions.send-tracking-link]
verify_jwt = false

[functions.request-delivery-address]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.verify-newsletter]
verify_jwt = false

[functions.verify-newsletter-confirm]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.submit-contact-form]
verify_jwt = false

[functions.get-payment-options]
verify_jwt = true

[functions.initialize-ghipss-payment]
verify_jwt = true

[functions.verify-ghipss-payment]
verify_jwt = true

[functions.ghipss-webhook]
verify_jwt = false