// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppyfrftmexvgnsxlhdbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBweWZyZnRtZXh2Z25zeGxoZGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODQ3NzYsImV4cCI6MjA3MDM2MDc3Nn0.iF81frkpEqDyrA8Ntfv6-Eyoy7r_BK8rpW_w07mcRl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});