// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { SUPABASE_CONFIG, checkSupabaseEnvironment } from '@/config/supabase';
import type { Database } from './types';

// Validate configuration on module load
checkSupabaseEnvironment();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_CONFIG.url, SUPABASE_CONFIG.anonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});