// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import { SUPABASE_CONFIG, checkSupabaseEnvironment } from '@/config/supabase';
import type { Database } from './types';

// Validate configuration on module load
checkSupabaseEnvironment();

// Check if running in native platform
const isNativePlatform = Capacitor.isNativePlatform();

// Log platform detection for debugging
console.log('[Supabase] Platform detection:', {
  isNative: isNativePlatform,
  platform: Capacitor.getPlatform(),
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_CONFIG.url, SUPABASE_CONFIG.anonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Disable URL session detection on native platforms to prevent issues
    detectSessionInUrl: !isNativePlatform,
  }
});